export const iconStrings = [
    "fa-solid fa-anchor",
    "fa-solid fa-flask",
    "fa solid fa-sun",
    "fa solid fa-hand-spock",
    "fa-regular fa-moon",
    "fa-regular fa-futbol",
    "fa-solid fa-car",
    "fa-solid fa-lira-sign",
    "fa-solid fa-snowflake",
    "fa-solid fa-bomb",
    "fa-solid fa-ghost",
    "fa-solid fa-fire",
    "fa-solid fa-virus",
    "fa-solid fa-guitar",
    "fa-solid fa-tree",
    "fa-solid fa-crown",
    "fa-solid fa-cake-candles",
    "fa-solid fa-hat-wizard",
];